[pytest]
testpaths = tests

addopts = --cov=app --cov-report=term-missing --cov-report=html -m "not e2e"

python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*

markers =
    slow: marks tests as slow
    fast: marks tests as fast
    e2e: marks tests as end-to-end

filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::ResourceWarning